---
driver:
  name: ec2
  use_sudo: false
  privileged: true
  aws_ssh_key_id: test-kitchen
  region: us-east-1
  security_group_ids: ["sg-ced059ba"]
  #availablity_zone: e
  #subnet_id: subnet-55a9516a
  #iam_profile_name: test-kitchen
  instance_type: t2.large
  associate_public_ip: true
  shared_credentials_profile: test-kitchen

transport:
  ssh_key: "~/.ssh/test-kitchen.pem"
  connection_timeout: 10
  connection_retries: 2


provisioner:
  name: ansible_playbook
  roles_path: ../ansible-os-ubuntu-14
  #requirements_path: requirements.yml
  hosts: all
  playbook: test.yml
  ansible_verbose: true
  ansible_verbosity: 4
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_ansible_omnibus: false
  ansible_connection: ssh
  require_chef_for_busser: false
  require_ruby_for_busser: false

platforms:
  - name: ubuntu-14.04
    transport:
      username: ubuntu   

suites:
  - name: test
    
#verifier:
#  name: inspec
#  sudo: true
#  inspec_tests:
#    - https://github.com/dev-sec/linux-baseline