---

  - name: 5.1.1 Ensure NIS is not installed (Scored)
    apt: name=nis state=absent purge=yes
    tags:
    - section5
    - section5.1
    - section5.1.1

  - name: 5.1.2.1 Ensure rsh, rlogin, rexec, talk, telnet, chargen, daytime, echo, discard, time is not enabled (stat inetd) (Scored)
    stat: path=/etc/inetd.conf
    register: inetd_path
    tags:
    - section5
    - section5.1
    - section5.1.2

  - name: 5.1.2.2 Ensure rsh, rlogin, rexec, talk, telnet, chargen, daytime, echo, discard, time is not enabled (Scored)
    lineinfile: >
        dest=/etc/inetd.conf
        regexp='^({{ item }}.*)'
        line='#\1'
        state=present
        backrefs=yes
        backup=yes
    with_items:
        - shell
        - login
        - exec
        - talk
        - ntalk
        - telnet
        - chargen
        - daytime
        - echo
        - discard
        - time
    when: inetd_path.stat.exists == True
    tags:
    - section5
    - section5.1
    - section5.1.2

  - name: 5.1.3.1 Ensure rsh client is not installed (Scored)
    apt: name=rsh-client state=absent purge=yes
    tags:
    - section5
    - section5.1
    - section5.1.3

  - name: 5.1.3.2 Ensure rsh client is not installed (Scored)
    apt: name=rsh-redone-client state=absent purge=yes
    tags:
    - section5
    - section5.1
    - section5.1.3

  - name: 5.1.5 Ensure talk client is not installed (Scored)
    apt: name=talk state=absent purge=yes
    tags:
    - section5
    - section5.1
    - section5.1.5

  - name: 5.1.8.1 Ensure xinetd is not enabled (stat xinetd) (Scored)
    stat: path=/etc/init/xinetd.conf
    register: xinetd_path
    tags:
    - section5
    - section5.1
    - section5.1.8

  - name: 5.1.8.2 Ensure xinetd is not enabled (Scored)
    lineinfile: >
        dest=/etc/init/xinetd.conf
        regexp='start on runlevel'
        state=present
        line='#start on runlevel [2345]'
    when: xinetd_path.stat.exists == True
    tags:
    - section5
    - section5.1
    - section5.1.8
